### ISSUE TITLE
Unable to user a complex type as Query parameter

### ISSUE THREAD

**Issue by bagbyte** [valoryteam/valory#6]
Given the following definitions:

```
export type Type1 = {
    amount: number;
    type: string;
}

export interface Type2 {
    amount: number;
    type: string;
}
```

Using `@Query('param'): Type1` produce the following error while building:

> Error: @Query('param') Can't support 'object' type. 

Using `@Query('param'): Type2` produce the following error while building:

> Error: @Query('param') Can't support 'refObject' type. 

Is there any way to achieve my goal?

If it's a `OpenAPI 2.0` limitation, would it be possible to support `OpenAPI 3.0` (maybe as configuration to choose from)?

**Comment by jfrconley** [comment]
Query params (like path and header) only support scalars and type aliases resolving to scalars.

Would fields in your request body satisfy your use case? If you really want to think of them as different parameters, you could use ```@BodyProp() prop: Type```. This will reference a specific property in body defaulting to the name of the parameter.

There is not a good standard way of handling complex objects in query params. That said, OA3 does have support for it but there are no current plans to upgrade.
