### ISSUE TITLE
Pattern validation produce an incorrect validation error JSON

### ISSUE THREAD

**Issue by bagbyte** [valoryteam/valory#7]
This is my code:

```
/**
 * Date type
 * @example "2019-10-20"
 * @format  string
 * @pattern ^\d{4}-(((0)[0-9])|((1)[0-2]))-([0-2][0-9]|(3)[0-1])$
 */
export type DateType = string;

@Route('test')
export class MyController extends Controller {
    @Get('foo') public foo(@Query('myDate') myDate: DateType) {
        return { code: 0 };
    }
}
```

When I call this API, if the format of `myDate` is correct, everything is ok, but if the format does not satisfy the regex I got the following response

> {"code":1001,"message":"ValidationError[pattern]: request.query.myDate should match pattern "^\d{4}-(((0)[0-9])|((1)[0-2]))-([0-2][0-9]|(3)[0-1])$""}

In the message, the double quotes from the regex are not escaped.

**Note:** adding the double quote surrounding the regex does not work either.

**Comment by jfrconley** [comment]
I'll look into this, likely an issue with JSDOC parsing
